theme = "personal-gruvbox"

[editor]
auto-format = false
line-number = "relative"
rulers = [81]
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
C-j = "normal_mode"

[keys.normal]
"space" = { w = ":write" }
"space" = { t = ":format" }
