import = ["/home/andrzej/.config/alacritty/base16-gruvbox-dark-hard-256.toml"]

[font]
size = 14.0

[font.normal]
family = "Iosevka"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 0

[window]
decorations = "none"
